/* Allegro datafile object indexes, produced by grabber v3.11 */
/* Datafile: c:\working\time.dat */
/* Date: Fri Mar 12 16:10:39 1999 */
/* Do not hand edit! */

#define BOX0_BMP                         0        /* BMP  */
#define BOX1_BMP                         1        /* BMP  */
#define BOX2_BMP                         2        /* BMP  */
#define BOX3_BMP                         3        /* BMP  */
#define BOXP0_PAL                        4        /* PAL  */
#define BOXP1_PAL                        5        /* PAL  */
#define BOXP2_PAL                        6        /* PAL  */
#define BOXP3_PAL                        7        /* PAL  */
#define DEAD_MIDI                        8        /* MIDI */
#define DEER_MIDI                        9        /* MIDI */
#define EVENT000_TXT                     10       /* TXT  */
#define EVENT001_TXT                     11       /* TXT  */
#define EVENT002_TXT                     12       /* TXT  */
#define EVENT003_TXT                     13       /* TXT  */
#define EVENT004_TXT                     14       /* TXT  */
#define EVENT005_TXT                     15       /* TXT  */
#define EVENT006_TXT                     16       /* TXT  */
#define EVENT007_TXT                     17       /* TXT  */
#define EVENT008_TXT                     18       /* TXT  */
#define EVENT009_TXT                     19       /* TXT  */
#define EVENT010_TXT                     20       /* TXT  */
#define EVENT011_TXT                     21       /* TXT  */
#define EVENT012_TXT                     22       /* TXT  */
#define EVENT013_TXT                     23       /* TXT  */
#define EVENT014_TXT                     24       /* TXT  */
#define EVENT015_TXT                     25       /* TXT  */
#define EVENT016_TXT                     26       /* TXT  */
#define EVENT017_TXT                     27       /* TXT  */
#define EVENT018_TXT                     28       /* TXT  */
#define EVENT019_TXT                     29       /* TXT  */
#define EVENT020_TXT                     30       /* TXT  */
#define EVENT021_TXT                     31       /* TXT  */
#define EVENT022_TXT                     32       /* TXT  */
#define EVENT023_TXT                     33       /* TXT  */
#define EVENT024_TXT                     34       /* TXT  */
#define EVENT025_TXT                     35       /* TXT  */
#define EVENT026_TXT                     36       /* TXT  */
#define EVENT027_TXT                     37       /* TXT  */
#define EVENT028_TXT                     38       /* TXT  */
#define EVENT029_TXT                     39       /* TXT  */
#define EVENT030_TXT                     40       /* TXT  */
#define EVENT031_TXT                     41       /* TXT  */
#define EVENT032_TXT                     42       /* TXT  */
#define EVENT033_TXT                     43       /* TXT  */
#define EVENT034_TXT                     44       /* TXT  */
#define EVENT035_TXT                     45       /* TXT  */
#define EVENT036_TXT                     46       /* TXT  */
#define EVENT037_TXT                     47       /* TXT  */
#define EVENT038_TXT                     48       /* TXT  */
#define EVENT039_TXT                     49       /* TXT  */
#define EVENT040_TXT                     50       /* TXT  */
#define EVENT041_TXT                     51       /* TXT  */
#define EVENT042_TXT                     52       /* TXT  */
#define EVENT043_TXT                     53       /* TXT  */
#define EVENT044_TXT                     54       /* TXT  */
#define EVENT045_TXT                     55       /* TXT  */
#define EVENT046_TXT                     56       /* TXT  */
#define EVENT047_TXT                     57       /* TXT  */
#define EVENT048_TXT                     58       /* TXT  */
#define EVENT049_TXT                     59       /* TXT  */
#define EVENT050_TXT                     60       /* TXT  */
#define EVENT051_TXT                     61       /* TXT  */
#define EVENT052_TXT                     62       /* TXT  */
#define EVENT053_TXT                     63       /* TXT  */
#define FOREST_MIDI                      64       /* MIDI */
#define GOTHIC_FONT                      65       /* FONT */
#define GRASS_MIDI                       66       /* MIDI */
#define GREY_PAL                         67       /* PAL  */
#define MAN000_BMP                       68       /* BMP  */
#define MAN001_BMP                       69       /* BMP  */
#define MAN002_BMP                       70       /* BMP  */
#define MAN010_BMP                       71       /* BMP  */
#define MAN011_BMP                       72       /* BMP  */
#define MAN012_BMP                       73       /* BMP  */
#define MAN100_BMP                       74       /* BMP  */
#define MAN101_BMP                       75       /* BMP  */
#define MAN102_BMP                       76       /* BMP  */
#define MAN110_BMP                       77       /* BMP  */
#define MAN111_BMP                       78       /* BMP  */
#define MAN112_BMP                       79       /* BMP  */
#define MAN200_BMP                       80       /* BMP  */
#define MAN201_BMP                       81       /* BMP  */
#define MAN202_BMP                       82       /* BMP  */
#define MAN210_BMP                       83       /* BMP  */
#define MAN211_BMP                       84       /* BMP  */
#define MAN212_BMP                       85       /* BMP  */
#define MAN300_BMP                       86       /* BMP  */
#define MAN301_BMP                       87       /* BMP  */
#define MAN302_BMP                       88       /* BMP  */
#define MAN310_BMP                       89       /* BMP  */
#define MAN311_BMP                       90       /* BMP  */
#define MAN312_BMP                       91       /* BMP  */
#define MAP0_BMP                         92       /* BMP  */
#define MAP1_BMP                         93       /* BMP  */
#define MAP2_BMP                         94       /* BMP  */
#define MENU_BMP                         95       /* BMP  */
#define MENU_MIDI                        96       /* MIDI */
#define OBJECT0_TXT                      97       /* TXT  */
#define OBJECT1_TXT                      98       /* TXT  */
#define OBJECT2_TXT                      99       /* TXT  */
#define PAINT_PAL                        100      /* PAL  */
#define SCARY_MIDI                       101      /* MIDI */
#define SPRITE0_BMP                      102      /* BMP  */
#define SPRITE1_BMP                      103      /* BMP  */
#define SPRITE2_BMP                      104      /* BMP  */
#define SPRITE3_BMP                      105      /* BMP  */
#define SPRITE4_BMP                      106      /* BMP  */
#define SPRITE5_BMP                      107      /* BMP  */
#define SPRITE6_BMP                      108      /* BMP  */
#define TITLE_BMP                        109      /* BMP  */
#define TITLE_FLI                        110      /* FLIC */
#define VILLAGE_MIDI                     111      /* MIDI */
#define WALK0_BMP                        112      /* BMP  */
#define WALK1_BMP                        113      /* BMP  */
#define WALK2_BMP                        114      /* BMP  */
#define WIN_MIDI                         115      /* MIDI */

